<?php
/**
 * Shortcode template for Momentum Screener — React version
 * All HTML is generated by React; this file only provides the mount point.
 */

if (!defined('ABSPATH')) {
    exit;
}

$lock_lookback  = !empty($atts['lock_lookback'])  && $atts['lock_lookback']  !== '0';
$lock_holding   = !empty($atts['lock_holding'])   && $atts['lock_holding']   !== '0';
$lock_topn      = !empty($atts['lock_topn'])      && $atts['lock_topn']      !== '0';
$lock_dividends = !empty($atts['lock_dividends']) && $atts['lock_dividends'] !== '0';
$lock_skip      = !empty($atts['lock_skip'])      && $atts['lock_skip']      !== '0';
$lock_vol       = !empty($atts['lock_vol'])       && $atts['lock_vol']       !== '0';
$lock_riskadj   = !empty($atts['lock_riskadj'])   && $atts['lock_riskadj']   !== '0';
$lock_return    = !empty($atts['lock_return'])    && $atts['lock_return']    !== '0';
?>
<div id="momentum-screener-root"
     class="momentum-screener-container"
     data-lookback="<?php echo esc_attr($atts['lookback']); ?>"
     data-holding="<?php echo esc_attr($atts['holding']); ?>"
     data-topn="<?php echo esc_attr($atts['topn']); ?>"
     data-lock-lookback="<?php echo $lock_lookback ? '1' : '0'; ?>"
     data-lock-holding="<?php echo $lock_holding ? '1' : '0'; ?>"
     data-lock-topn="<?php echo $lock_topn ? '1' : '0'; ?>"
     data-lock-dividends="<?php echo $lock_dividends ? '1' : '0'; ?>"
     data-lock-skip="<?php echo $lock_skip ? '1' : '0'; ?>"
     data-lock-vol="<?php echo $lock_vol ? '1' : '0'; ?>"
     data-lock-riskadj="<?php echo $lock_riskadj ? '1' : '0'; ?>"
     data-lock-return="<?php echo $lock_return ? '1' : '0'; ?>">
    <div class="ms-loading">
        <div class="ms-spinner"></div>
        <p><?php esc_html_e('Загрузка данных...', 'momentum-week'); ?></p>
    </div>
</div>
